/**
 * 来源 G$a / E$a / F$a / r$ / s$。把长位置参数列表改为声明式任务目录。
 * reportFlag 只按已确认的遥测字段命名，不猜测产品含义。
 * target 是 URL 适配器的键，不是可直接访问的资源地址。
 */
export const TASK_DEFINITIONS = [
  {
    id: "metadata-sync",
    enabledFlag: "esmst",
    periodFlag: "mstpim",
    reportType: 4,
    priority: 0,
    reportFlag: true,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "metadata",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "service-worker-update",
    enabledFlag: "esbst",
    periodFlag: "swutpim",
    reportType: 16,
    priority: 1,
    reportFlag: true,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "taskIframe",
    taskType: "service_worker_update",
    requiresNetwork: true,
    requiresAuth: false,
    requiresEligibility: false,
  },
  {
    id: "drive-service-worker",
    enabledFlag: "edswut",
    periodFlag: "dswutpim",
    reportType: 13,
    priority: 1,
    reportFlag: true,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "driveSwUpdate",
    taskType: "drive_service_worker_update",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "homescreen-cello-sync",
    enabledFlag: "eshcst",
    periodFlag: "hcstpim",
    reportType: 2,
    priority: 2,
    reportFlag: true,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "documentBackgroundSync",
    taskType: "homescreen_cello_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "drive-cello-sync",
    enabledFlag: "esdcst",
    periodFlag: "dcstpim",
    reportType: 1,
    priority: 2,
    reportFlag: true,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "driveBackgroundSync",
    taskType: "drive_cello_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "local-changes-sync",
    enabledFlag: "eslcst",
    periodFlag: "lcstpim",
    reportType: 5,
    priority: 1,
    reportFlag: false,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "local_changes_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: false,
  },
  {
    id: "auto-sync",
    enabledFlag: "esast",
    periodFlag: "astpim",
    reportType: 6,
    priority: 3,
    reportFlag: false,
    accelerateUntilFirstSuccess: false,
    context: 1,
    target: "syncWorker",
    taskType: "auto_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "webfonts-sync",
    enabledFlag: "eswst",
    periodFlag: "wstpim",
    reportType: 8,
    priority: 2,
    reportFlag: true,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "webfonts_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "impression-sync",
    enabledFlag: "esist",
    periodFlag: "istpim",
    reportType: 7,
    priority: 4,
    reportFlag: false,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "impressionSync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: false,
  },
  {
    id: "document-deletion",
    enabledFlag: "esddt",
    periodFlag: "ddtpim",
    reportType: 9,
    priority: 4,
    reportFlag: false,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "doc_deletion",
    requiresNetwork: false,
    requiresAuth: false,
    requiresEligibility: false,
  },
  {
    id: "update-unsaved-changes",
    enabledFlag: "esuuct",
    periodFlag: "uuctpim",
    reportType: 10,
    priority: 4,
    reportFlag: false,
    accelerateUntilFirstSuccess: true,
    context: 2,
    target: "taskIframe",
    taskType: "update_unsaved_changes",
    requiresNetwork: false,
    requiresAuth: false,
    requiresEligibility: false,
  },
  {
    id: "cleanup-task",
    enabledFlag: "esct",
    periodFlag: "ctpim",
    reportType: 11,
    priority: 4,
    reportFlag: false,
    accelerateUntilFirstSuccess: true,
    context: 2,
    target: "taskIframe",
    taskType: "cleanup",
    requiresNetwork: false,
    requiresAuth: false,
    requiresEligibility: false,
  },
  {
    id: "report-task",
    enabledFlag: "esrt",
    periodFlag: "rtpim",
    reportType: 14,
    priority: 4,
    reportFlag: false,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "taskIframe",
    taskType: "report",
    requiresNetwork: false,
    requiresAuth: false,
    requiresEligibility: false,
  },
  {
    id: "sync-objects-sync",
    enabledFlag: "esost",
    periodFlag: "sostpim",
    reportType: 15,
    priority: 2,
    reportFlag: true,
    accelerateUntilFirstSuccess: true,
    context: 1,
    target: "syncWorker",
    taskType: "sync_objects_sync",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
  {
    id: "odp-service-worker",
    enabledFlag: "eodpswut",
    periodFlag: "odpswutpim",
    reportType: 19,
    priority: 1,
    reportFlag: true,
    accelerateUntilFirstSuccess: false,
    context: 2,
    target: "odpWorker",
    taskType: "one_details_pane_service_worker_update",
    requiresNetwork: true,
    requiresAuth: true,
    requiresEligibility: true,
  },
];
for (const definition of TASK_DEFINITIONS) Object.freeze(definition);
Object.freeze(TASK_DEFINITIONS);

export function buildTaskCatalog(flags, urls) {
  const tasks = [];
  for (const definition of TASK_DEFINITIONS) {
    if (!flags.boolean("docs-offline-" + definition.enabledFlag)) continue;
    const periodKey = "docs-offline-" + definition.periodFlag;
    if (!(flags.number(periodKey) > 0)) continue;
    const executorUrl = urls[definition.target]();
    tasks.push({
      id: definition.id,
      priority: definition.priority,
      periodMinutes: flags.number(periodKey),
      reportType: definition.reportType,
      reportFlag: definition.reportFlag,
      accelerateUntilFirstSuccess: definition.accelerateUntilFirstSuccess,
      execution: {
        context: definition.context,
        executorUrl,
        taskType: definition.taskType,
        timeoutMs: 300_000,
        requiresNetwork: definition.requiresNetwork,
        requiresAuth: definition.requiresAuth,
        requiresEligibility: definition.requiresEligibility,
        parameters: null,
      },
    });
  }
  return tasks;
}
